apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-deployment
spec:
  selector:
    matchLabels:
      app: blue-vite-app
  replicas: 3
  template:
    metadata:
      labels:
        app: blue-vite-app
        version: blue
    spec:
      containers:
        - name: blue-vite-app-container
          image: blue-vite-app-image:blue
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
