apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-deployment
spec:
  selector:
    matchLabels:
      app: canary-app
      version: canary
  replicas: 1
  template:
    metadata:
      labels:
        app: canary-app
        version: canary
    spec:
      containers:
        - name: canary-app-deployment-container
          image: canary-app-deployment-image:canary
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
