apiVersion: apps/v1
kind: Deployment Rolling and Recreate
metadata:
  name: imrans-vite-app-deployment
spec:
  selector:
    matchLabels:
      app: imrans-vite-app
  replicas: 3
  template:
    metadata:
      labels:
        app: imrans-vite-app
    spec:
      containers:
        - name: imrans-vite-app-container
          image: imrans-vite-app-image:latest
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
